// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservationSystem.Domain.DBContext;

#nullable disable

namespace ReservationSystem.Domain.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20240716135935_Initial-Commit")]
    partial class InitialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.SearchAvailabilityResults", b =>
                {
                    b.Property<long>("result_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("result_id"));

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("request")
                        .HasColumnType("jsonb");

                    b.Property<string>("response")
                        .HasColumnType("jsonb");

                    b.Property<int?>("total_results")
                        .HasColumnType("integer");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("result_id");

                    b.ToTable("availibility_results");
                });
#pragma warning restore 612, 618
        }
    }
}
