// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservationSystem.Domain.DBContext;

#nullable disable

namespace ReservationSystem.Domain.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20241205171449_AddReservationFlowTable")]
    partial class AddReservationFlowTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.FlightMarkup", b =>
                {
                    b.Property<long>("markup_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("markup_id"));

                    b.Property<decimal?>("adult_markup")
                        .HasColumnType("numeric");

                    b.Property<string>("airline")
                        .HasColumnType("text");

                    b.Property<bool?>("apply_airline_discount")
                        .HasColumnType("boolean");

                    b.Property<bool?>("apply_markup")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("child_markup")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("created_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("discount_on_airline")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("discount_on_meta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("infant_markup")
                        .HasColumnType("numeric");

                    b.Property<string>("meta")
                        .HasColumnType("text");

                    b.HasKey("markup_id");

                    b.ToTable("flight_markup");
                });

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.ReservationFlow", b =>
                {
                    b.Property<long>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("auto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AutoId"));

                    b.Property<string>("AmadeusSessionId")
                        .HasColumnType("text")
                        .HasColumnName("amadeus_session_id");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool?>("IsError")
                        .HasColumnType("boolean")
                        .HasColumnName("is_error");

                    b.Property<string>("Request")
                        .HasColumnType("jsonb")
                        .HasColumnName("request");

                    b.Property<string>("RequestName")
                        .HasColumnType("text")
                        .HasColumnName("request_name");

                    b.Property<string>("Response")
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("AutoId");

                    b.ToTable("reservation_flow");
                });

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.SearchAvailabilityResults", b =>
                {
                    b.Property<long>("result_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("result_id"));

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("request")
                        .HasColumnType("jsonb");

                    b.Property<string>("response")
                        .HasColumnType("jsonb");

                    b.Property<int?>("total_results")
                        .HasColumnType("integer");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("result_id");

                    b.ToTable("availibility_results");
                });
#pragma warning restore 612, 618
        }
    }
}
