// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservationSystem.Domain.DBContext;

#nullable disable

namespace ReservationSystem.Domain.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20250118161350_UpdateMarkupTable")]
    partial class UpdateMarkupTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservationApi.ReservationSystem.Domain.DB_Models.BookingInfo", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("auto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AutoId"));

                    b.Property<string>("BookingRef")
                        .HasColumnType("text")
                        .HasColumnName("booking_ref");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<string>("PnrNumber")
                        .HasColumnType("text")
                        .HasColumnName("pnr_number");

                    b.Property<bool?>("SentEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("sent_email");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("AutoId");

                    b.ToTable("booking_info");
                });

            modelBuilder.Entity("ReservationApi.ReservationSystem.Domain.DB_Models.ManualPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("BookingRef")
                        .HasColumnType("text")
                        .HasColumnName("booking_ref");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool?>("PaymentStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("payment_status");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.HasKey("PaymentId");

                    b.ToTable("manual_payment");
                });

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.FlightInfo", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlightId"));

                    b.Property<string>("AmadeusSessionId")
                        .HasColumnType("text")
                        .HasColumnName("amadeus_session_id");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("arrival_time");

                    b.Property<string>("CabinClass")
                        .HasColumnType("text")
                        .HasColumnName("cabin_class");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Departure")
                        .HasColumnType("text")
                        .HasColumnName("departure");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("departure_time");

                    b.Property<string>("Destination")
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("text")
                        .HasColumnName("flight_number");

                    b.Property<string>("FlightOffer")
                        .HasColumnType("jsonb")
                        .HasColumnName("flight_offer");

                    b.HasKey("FlightId");

                    b.ToTable("flight_info");
                });

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.FlightMarkup", b =>
                {
                    b.Property<long>("MarkupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("markup_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MarkupId"));

                    b.Property<decimal?>("AdultMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("adult_markup");

                    b.Property<string>("Airline")
                        .HasColumnType("text")
                        .HasColumnName("airline");

                    b.Property<decimal?>("AirlineMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("airline_markup");

                    b.Property<bool?>("ApplyAirlineDiscount")
                        .HasColumnType("boolean")
                        .HasColumnName("apply_airline_discount");

                    b.Property<bool?>("ApplyMarkup")
                        .HasColumnType("boolean")
                        .HasColumnName("apply_markup");

                    b.Property<string>("BetweenHours")
                        .HasColumnType("text")
                        .HasColumnName("between_hours");

                    b.Property<decimal?>("BetweenHoursMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("between_hours_markup");

                    b.Property<decimal?>("ChildMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("child_markup");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on");

                    b.Property<decimal?>("DiscountOnAirline")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_on_airline");

                    b.Property<decimal?>("DiscountOnMeta")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_on_meta");

                    b.Property<string>("EndAirport")
                        .HasColumnType("text")
                        .HasColumnName("end_airport");

                    b.Property<decimal?>("EndAirportMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("end_airport_markup");

                    b.Property<string>("FareType")
                        .HasColumnType("text")
                        .HasColumnName("fare_type");

                    b.Property<decimal?>("FareTypeMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("fare_type_markup");

                    b.Property<string>("Gds")
                        .HasColumnType("text")
                        .HasColumnName("gds");

                    b.Property<decimal?>("GdsMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("gds_markup");

                    b.Property<decimal?>("InfantMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("infant_markup");

                    b.Property<bool?>("IsPercentage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_percentage");

                    b.Property<string>("JournyType")
                        .HasColumnType("text")
                        .HasColumnName("journy_type");

                    b.Property<decimal?>("JournyTypeMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("journy_type_markup");

                    b.Property<string>("MarketingSource")
                        .HasColumnType("text")
                        .HasColumnName("marketing_source");

                    b.Property<decimal?>("MarketingSourceMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("marketing_source_markup");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<decimal?>("MetaMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("meta_markup");

                    b.Property<string>("StartAirport")
                        .HasColumnType("text")
                        .HasColumnName("start_airport");

                    b.Property<decimal?>("StartAirportMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("start_airport_markup");

                    b.HasKey("MarkupId");

                    b.ToTable("flight_markup");
                });

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.PassengerInfo", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PassengerId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DOB")
                        .HasColumnType("text")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsLead")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PassengerType")
                        .HasColumnType("text")
                        .HasColumnName("passenger_type");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.HasKey("PassengerId");

                    b.HasIndex("FlightId");

                    b.ToTable("passenger_info");
                });

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.ReservationFlow", b =>
                {
                    b.Property<long>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("auto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AutoId"));

                    b.Property<string>("AmadeusSessionId")
                        .HasColumnType("text")
                        .HasColumnName("amadeus_session_id");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on");

                    b.Property<bool?>("IsError")
                        .HasColumnType("boolean")
                        .HasColumnName("is_error");

                    b.Property<string>("Request")
                        .HasColumnType("jsonb")
                        .HasColumnName("request");

                    b.Property<string>("RequestName")
                        .HasColumnType("text")
                        .HasColumnName("request_name");

                    b.Property<string>("Response")
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("AutoId");

                    b.ToTable("reservation_flow");
                });

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.SearchAvailabilityResults", b =>
                {
                    b.Property<long>("result_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("result_id"));

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("request")
                        .HasColumnType("jsonb");

                    b.Property<string>("response")
                        .HasColumnType("jsonb");

                    b.Property<int?>("total_results")
                        .HasColumnType("integer");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("result_id");

                    b.ToTable("availibility_results");
                });

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ReservationSystem.Domain.Models.Enquiry.Enquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_no");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("ReservationSystem.Domain.DB_Models.PassengerInfo", b =>
                {
                    b.HasOne("ReservationSystem.Domain.DB_Models.FlightInfo", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
